version: '2'

services:
  vue:
    command: "yarn run dev"
    image: ssr.vue:1
    build:
      dockerfile: docker/Dockerfile
      context: ./
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./app:/opt/app